
global_costmap:
  global_frame: map
  update_frequency: 15.0
  publish_frequency: 5.0
  plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: depth_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}