local_costmap:
  update_frequency: 15.0
  publish_frequency: 10.0
  rolling_window: true
  width: 8.0
  height: 8.0
  resolution: 0.05
  plugins:
  - {name: depth_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}