TrajectoryPlannerROS:
  acc_lim_x: 0.75
  acc_lim_y: 0
  acc_lim_theta: 0.9

  max_vel_x: 0.85
  min_vel_x: 0.6
  max_vel_theta: 0.7
  min_vel_theta: -0.7
  min_in_place_vel_theta: 0.65

  escape_vel: -0.7
  escape_reset_dist: 0.05
  yaw_goal_tolerance: 0.4  # in rads
  xy_goal_tolerance: 0.4  # in meters
  latch_xy_goal_tolerance: false

  holonomic_robot: false

  vx_samples: 3
  meter_scoring: true

  path_distance_bias: 0.75
  goal_distance_bias: 1.0
  occdist_scale: 0.01
  dwa: true